name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Check and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly

      - name: Check
        run: cargo check --all --all-targets

      - name: Test
        run: cargo test
